### PR TITLE
always use the google-java-format if the plugin is installed.

### PR DESCRIPTION
**Pull request by patflynn**
@aslo 
@etanshaul 

let me know if you guys think this is a bad idea.

### CODE REVIEW

**Comment by etanshaul** [comment]
is the commit message correct? I don't see how having the plugin installed affects this.

**Comment by aslo** [comment]
This looks like just setting the google-java-format for developing the plugin. Is that the intent?

**Comment by patflynn** [comment]
Correct. This change just turns on google-java-format plugin if it's installed in the IntelliJ that you're using to edit google-cloud-intellij

**Comment by joaoandremartins** [comment]
I'm guessing we'd also need to first download and install google-java-format to make this work.

SG, though I've been running into issues with the way google-java-format organises imports. It's incompatible with checkstyle, so I usually fall back to the IJ code style for imports, which is almost what checkstyle requires (need to add some new lines here and there)

**Comment by patflynn** [comment]
Yeah this will only apply if you happen to have the plugin install, which on our work IJ instances it is by default. 

I'll take a look at the imports issue, may just fix that by modifying linting.

**Pull request merged**
