### PR TITLE
Reduce log level for a common exception to avoid plugin crash reporting.

### LINKED ISSUE #2233: Unhandled network exception when setting a breakpoint
Reported by a user.

Description
exception setting a breakpoint: Network is unreachable (connect failed)
Stack trace:
java.net.ConnectException: Network is unreachable (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.cloud.tools.intellij.stackdriver.debugger.CloudDebugProcessStateController.lambda$setBreakpointAsync$2(CloudDebugProcessStateController.java:262)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception class name:
java.net.ConnectException
Exception message:
exception setting a breakpoint: Network is unreachable (connect failed)
Throw file name:
PlainSocketImpl.java
Throw line number:
-2
Throw class name:
java.net.PlainSocketImpl
Throw method name:
socketConnect
Submitted on:
August 11, 2018 07:39 (Time)
August 11, 2018 04:39 (PDT)
Product Version:
2018.1.4

### PR DESCRIPTION
**Pull request by ivanporty**
Fixes #2233.

IDE's `error()` reports an error as a fatal one, causing this error report to be created. Network exceptions are expected and should be handled properly with a simple warning.

### CODE REVIEW

**Comment by etanshaul** [comment]
I'm tempted to say to leave the log level as it is so that we can at least see what the error is. If debugger API changes, for example, this is exception would still be triggered no? In this case it would be nice to know. We can always ignore the ones that we know are not something to be fixed. wdyt?

**Comment by ivanporty** [comment]
I see your point and I agree we need to know about unusual and new exceptions here. But, looking at the code here, the only thing handled is standard `IOException`, and since it must be triggered when some sort of network issue occurred, it doesn't seem like a perfect candidate for a plugin level error report. On the other hand, should a new error type be introduced, it won't be caught anymore, and we will definitely get an error report from here. Let me know if this still makes sense, I'm pretty sure this error is quite rare and we won't get flooded by this error messages anyway - just need to make sure we won't try to fix this again when we get a new report.

**Comment by etanshaul** [comment]
yeah since its IOException then what you're saying makes sense. I assume `handler.onError` will provide the user some kind of nice error indication?

**Comment by ivanporty** [comment]
I think handler just logs an error message but this is probably enough - visual feedback would be breakpoint not being set and details are network issue logged.

**Pull request merged**
