### PR TITLE
Committing project structure changes causing local vcs conflicts

### LINKED ISSUE #1239: Opening our project locally creates VCS changes
for example, just opening the project and doing nothing causes a local change in `compiler.xml`

We should figure out why and fix it (either commit the change or change the project somehow).

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #1239

### CODE REVIEW

**Comment by patflynn** [comment]
Does this turn off error prone?

**Comment by etanshaul** [comment]
Error prone still runs when building the plugin. I'm check to see if this caused any IDE inspections to be removed.

**Comment by joaoandremartins** [comment]
These are the changes the IDE always applies by default, which make me have to stash all the time.
They're always on in my local environment and I haven't seen any issues.

**Comment by etanshaul** [comment]
@patflynn I'm not seeing any changes with regards to inspections within the IDE (there were none before), and as I mentioned error prone still runs.

**Pull request merged**
