### PR TITLE
Update core lib

### PR DESCRIPTION
**Pull request by aslo**
* Update the core lib version to 0.1.11
* Perform minimal changes to `AppEngineServerModel` in order to fix breaking changes

### CODE REVIEW

**Comment by etanshaul** [comment]
can you explain the changes to `AppEngineServerModel` and how that relates to upgrading the core lib?

**Comment by aslo** [comment]
@etanshaul Sure. The changes in the core lib include [this commit](https://github.com/GoogleCloudPlatform/appengine-plugins-core/commit/c1be9b8d604dee7a8ef593b339bc796826a46ee2), which adds  a `getJavaHomeDir` method to the `RunConfiguration` interface. 

This PR aims to do as little as possible beyond just upgrading the library - it implements that `getJavaHomeDir` method (so the code can compile) by making the javaHomeDir setting part of the internal `AppEngineModelSettings` class.

**Comment by etanshaul** [comment]
oh cool. I didn't realize at first that RunConfiguration was part of the common-lib.

lgtm

**Comment by aslo** [comment]
I think you also need to do a github review in order to unblock merging of this PR. Thanks!

**Comment by etanshaul** [comment]
nice, I didn't know this blocked the merged. just approved

**Pull request merged**
