### PR TITLE
Update cloud API action wording

### LINKED ISSUE #2249: Make Cloud API action wording more unified for IDEA and non-IDEA IDEs
This is regarding the wording on the cloud tools menu action.

1) Currently for IDEA maven project the wording is: `Add Cloud libraries ...`
2) For all other IDEs (and IDEA without maven) is: `Manage Cloud APIs ...`

To make this a bit more consistent, I'm proposing:

1) `Add and Manage Cloud APIs ...`
2) `Manage Cloud APIs ...`

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #2249

### CODE REVIEW

**Comment by ivanporty** [comment]
I'm slightly concerned we leave "Libraries" out - it was pretty helpful for this case. How about `Manage Cloud APIs and Libraries...`?

**Comment by etanshaul** [comment]
what about:

1) `Add Cloud Libraries and Manage Cloud APIs`
2) `Manage Cloud APIs`

its a bit long, but its the most descriptive / correct. wdyt?

**Comment by ivanporty** [comment]
Looks good to me, I agree.

**Comment by etanshaul** [comment]
updated

**Pull request merged**
