### PR TITLE
 Get rid of redundant facet check on app engine local run; add artifact guidance wording

### PR DESCRIPTION
**Pull request by etanshaul**
This check is not needed because the facet is already confirmed prior to adding it to the target deployable dropdown (if it didn't have this facet, it would not have shown up in the dropdown to begin with):

image

### CODE REVIEW

**Comment by ivanporty** [comment]
So in case we don't have this facet, we won't have this (implied) drop down, but just an error message - `Artifact isn't specified`, correct?

**Comment by etanshaul** [comment]
correct

**Comment by ivanporty** [comment]
So if I try to add an App Engine Standard target when project is App Engine Flex, it gives me empty drop-down for Artifact and `Artifact isn't specified` error. Is it clear enough to suggest what I did wrong here? Maybe expand that error a bit to make it easier to understand what is `Artifact` in this case and how to fix it?

**Comment by etanshaul** [comment]
Yeah good idea. The usually is generally steered away from opening a local dev server run config for flex (they are blocked from the tools menu shortcut, and it shows up as hidden by default when manually adding the run config), but some detailed wording here is a good idea. I'll add it.

**Comment by etanshaul** [comment]
@ivanporty @patflynn 

Added some guiding wording:

image

**Comment by etanshaul** [comment]
On second look. Maybe I'll add something about requiring exploded-war artifacts too.

**Comment by etanshaul** [comment]
Updated the wording and added some line breaks. let me know what you think.

image

**Comment by etanshaul** [comment]
screenshot above is updated to reflect all the wording changes

**Comment by ivanporty** [comment]
That's awesome, would be really helpful for a confused user!

**Pull request merged**
