### PR TITLE
Adds Flexible support documentation.

### PR DESCRIPTION
**Pull request by joaoandremartins**

### CODE REVIEW

**Comment by joaoandremartins** [comment]
We should figure out what we want to do with https://googlecloudplatform.github.io/google-cloud-intellij/

This piece of documentation should become available from https://googlecloudplatform.github.io/google-cloud-intellij/flexible-tutorial

**Comment by etanshaul** [comment]
shall we iterate on this in the doc? might be easier than here on github

**Comment by joaoandremartins** [comment]
Sounds good to me.

**Comment by etanshaul** [comment]
comments added to the doc

**Comment by etanshaul** [comment]
feel free to sync with the changes in the doc and merge into the docs folder

**Pull request merged**
