### PR TITLE
Release v16.11.2

### PR DESCRIPTION
**Pull request by etanshaul**

### CODE REVIEW

**Comment by patflynn** [comment]
Did we include
https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1123

**Comment by joaoandremartins** [comment]
Nope. We need to bump the common library version to 0.2.2. Planning to do so in #1096.

**Comment by etanshaul** [comment]
Can we bump the version separately so we can get that fix in for this release?

**Comment by joaoandremartins** [comment]
I was trying to plug a code review for my PR. But yeah, that makes more sense. :)

**Comment by etanshaul** [comment]
cool. I'll do one more release once we can merge this in.

**Comment by aslo** [comment]
I just created a PR with the bumped versoin: https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1126

**Pull request merged**
