### PR TITLE
Catch invalid java sdk validation exception from core lib.

### PR DESCRIPTION
**Pull request by etanshaul**
I'm not 100% on if this is the best approach. WDYT?

Also need some tests.

### CODE REVIEW

**Comment by etanshaul** [comment]
fixes #1602

**Comment by nkibler** [comment]
I like it, it's better than throwing an IDE error IMO. Think you can get tests in this PR too?

**Comment by etanshaul** [comment]
https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/441

**Comment by etanshaul** [comment]
On second thought - I think perhaps the better solution here is, on SDK validation, to pass in the project JDK to the CloudSDK builder (like we do for "normal" non-validation-only scenarios). 

This would be in addition to catching the core-lib exception.

**Comment by nkibler** [comment]
Oh interesting, I didn't know that was an option. Yeah I agree, especially if we're doing that normally for other commands.

**Comment by nkibler** [comment]
Ah I see, yeah then let's wait to hear from them about decoupling these two. If they don't want to decouple them, would you still be in support of the solution in this PR? It basically moves a user error (messed up system JDK) from being an IDE error to being a validation error; we still show it, it's just about how we show it and if it gets reported as a crash to us.

**Comment by etanshaul** [comment]
"them" is actually us :)

I'll think about it. Talking to @patflynn offline another thing we could do is just not validate the jdk in the core lib.

**Comment by patflynn** [comment]
@etanshaul close or merge?

**Comment by etanshaul** [comment]
this requires changes to the core library prior to merging, and could affect other tooling too. I need to revisit that before making the decision here

**Pull request closed without merging**
