### PR TITLE
Convention is to include '...' after tools menu action labels.

### PR DESCRIPTION
**Pull request by patflynn**

### CODE REVIEW

**Comment by etanshaul** [comment]
I need to check this, but I think I explicitly included or did not include these for a reason: for instance if the local run config is already configured, then it runs it immediately (no subsequent UI panel pops up).

**Comment by etanshaul** [comment]
Yea - create a new AE standard project, configured the local run server, then choose this option from the menu.

Notice that the server runs immediately.

I guess having ellipses here is still up for debate; but I used them to indicate that the action will or will not execute immediately.

**Comment by patflynn** [comment]
I'm closing this based off of @etanshaul distinction between the action types.

**Comment by etanshaul** [comment]
I think you forgot to close it; closing

**Pull request closed without merging**
