### PR TITLE
Use java.nio.file.Path for displaying system-independent paths

### LINKED ISSUE #766: on windows my path separators in the custom app  engine flex deployment file UI switched
The default path was c:/bla/blab/bla and when I used the widget to select another file it switched to c:\bla\bla. 

(could have been the other way around)

### PR DESCRIPTION
**Pull request by aslo**
fixes #766

@joaoandremartins FYI this is similar to the work that you are doing in https://github.com/GoogleCloudPlatform/gcloud-intellij/pull/857.

### CODE REVIEW

**Comment by aslo** [comment]
@joaoandremartins @patflynn @etanshaul please take a look.

**Comment by joaoandremartins** [comment]
These changes are already in #857. Unless these need to go out immediately, I would suggest waiting for my PR to be submitted.

It's pending on a change at the CloudSdk level where we don't want to have to initialize a CloudSdk object just to verify a Cloud SDK path, but if urgent, I can push my PR and open a new issue to refactor that CloudSdk bit.

**Comment by aslo** [comment]
Actually, these changes aren't in #857 - if you look at the same section in [your PR's diff](https://github.com/GoogleCloudPlatform/gcloud-intellij/pull/857/files#diff-1ffab44e777b8735ecc22d775aeb8556L162), it's actually unchanged. 

If you want to ship these changes along with your PR, feel free to apply these changes to it and I'll close this one. Otherwise, we can do them separately (there's no rush on these changes).

**Comment by etanshaul** [comment]
@aslo just wondering if you tested this on a windows machine?

**Comment by aslo** [comment]
I did - tested on a compute engine windows server VM. I was able to replicate the bug and verify that it's fixed by these changes. Now, when opening the App Engine Flex Deployment Configuration dialog, the default paths use the correct path separator from the beginning.

**Comment by patflynn** [comment]
LGTM

**Comment by etanshaul** [comment]
:ship:

**Comment by aslo** [comment]
Added another trivial commit to retrigger travis builds. It appears that commits made via the "Update branch" button do not cause travis builds to run.

**Pull request merged**
