### PR TITLE
Remove application and version from appengine-web.xml template

### LINKED ISSUE #827: App Engine Standard new project template should not include version and application elements
Those are now passed as arguments to deployment rather than configured in the xml file.

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #827 

Should not be merged until gcloud is updated .

This removes `application` and `version` from all `appengine-web.xml` template files (including test data).

It also updates the appengine-web xsd (see the link from here: https://cloud.google.com/appengine/docs/java/config/appref).

### CODE REVIEW

**Comment by aslo** [comment]
LGTM!

**Comment by etanshaul** [comment]
todo: prior to merging confirm that the updated xsd is still the latest one.

**Comment by etanshaul** [comment]
looks like this is now supported by gcloud 131

**Comment by patflynn** [comment]
@etanshaul I think it's time.

**Comment by etanshaul** [comment]
This is ready for review. However, even though gcloud supports it now, I think we should wait for https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1051 to go in first

**Comment by etanshaul** [comment]
@patflynn @joaoandremartins @aslo 

This is ready for review. Now that we have a minimum sdk version check this can be merged in.

**Comment by patflynn** [comment]
Can we merge this and update the release notes?

**Pull request merged**
