### PR TITLE
GAE framework support no longer adds local devserver library to dependencies list

### LINKED ISSUE #945: Creating a new App Engine project using the IJ wizard for Java EE projects creates a broken dev appserver config
Steps to reproduce:
1) file -> new project
2)  select 'Java Enterprise' in left margin panel
3) select Google App Engine in the right panel and click next.
4) observe that the local server run configuration has a red 'x' on it and fails when you run it.
5) observe that the local server is listed twice as a library in the module dependencies settings.

### PR DESCRIPTION
**Pull request by joaoandremartins**
Only application server does that now for Java EE projects.

Fixes #945

### CODE REVIEW

**Comment by joaoandremartins** [comment]
In this state, `AppEngineUltimateWebIntegration.addDevServerToModuleDependencies()` will be unused code. I'm wondering if I should remove that too?
We could use possibly use it again if IJ were to check if a dependency already exists in a module before adding it again, but I'm not sure if or when that will happen..

**Comment by aslo** [comment]
Just curious, where does the remaining dev server dependency get added?

**Comment by joaoandremartins** [comment]
The responsible for adding duplicate libraries is https://github.com/JetBrains/intellij-community/blob/master/java/idea-ui/src/com/intellij/ide/util/newProjectWizard/AddSupportForFrameworksPanel.java#L449

For Java EE projects, `selectedFrameworks` will have size 3: "Application Server" , "Web Application", and "Google App Engine". Java projects don't have the "Application Server" bit.

We're always adding the library on our side using the Google App Engine part, through `AppEngineSupportProvider.addSupport()`. Adding the library for the Application Server is completely contained in the framework. I think it only uses `AppEngineServerHelper.getApplicationServerInfo()` to grab the dependency name and contained libraries. I couldn't spot anywhere we have any control over this, and couldn't discover any reliable hack on AppEngineSupportProvider to not add the library if it's already added. (addSupport() is called in different order on different runs, so sometimes you'd see two dependencies, sometimes one)

**Comment by aslo** [comment]
Interesting, thanks!

**Pull request merged**
