### PR TITLE
Rebump version number in release notes.

### PR DESCRIPTION
**Pull request by joaoandremartins**
And check if you want to add anything else.

### CODE REVIEW

**Comment by etanshaul** [comment]
why do we need to bump it again? lgtm in any case

**Comment by joaoandremartins** [comment]
I think release 16.11.3 doesn't contain a lot of the latest fixes we've launched and a new release is necessary?

I actually thought the release would only get going from the moment your bump PR went through. Since that's not true, I think we need a new release.

**Comment by joaoandremartins** [comment]
Also, I'll hold off on @patflynn since he might have something to add.

**Comment by etanshaul** [comment]
oh ok. I thought you already released today with the new changes.

**Comment by etanshaul** [comment]
btw check out the release page: https://github.com/GoogleCloudPlatform/google-cloud-intellij/releases
 to see what the release contains. Looks like there have been 9 commits since 16.11.3.

**Comment by patflynn** [comment]
I was just saying it needs to be 4 since 3 is already cut, and 4 is going
to be the next RC with the latest bug fixes.

**Pull request merged**
