### PR TITLE
default compiler to error prone.

### PR DESCRIPTION
**Pull request by patflynn**
I know etan changed removed this recently.

Can you check that your compiler is set to error prone in settings?

### CODE REVIEW

**Comment by etanshaul** [comment]
It is not set to error prone:

image

I do still get error prone messages when building the project.

Are you not?

**Comment by patflynn** [comment]
You need to set the internal compile to error prone to get the 'in-editor'
(red squiggly lines) error-prone errors.

Have you installed the plugin?

**Comment by patflynn** [comment]
capture

**Comment by patflynn** [comment]
BTW I think the plugin is installed by default on our work intellij

**Comment by etanshaul** [comment]
I do not have the error prone plugin installed. 

And I did test out getting in-editor validation before and after removing the compiler setting and never got them, which is why I was comfortable with the change. I'll try it out again.

**Comment by joaoandremartins** [comment]
I don't see that errorprone option in the Java compiler settings.
I also can't find the error prone plugin in the plugins list.

**Comment by etanshaul** [comment]
oh..I guess the plugin would be required for this right? hence the vcs conflicts when the setting is there, but the plugin is not installed. this makes more sense. my only hesitation is that now developers are required to have the errorprone plugin to avoid these conflicts

**Comment by etanshaul** [comment]
@joaoandremartins the error prone plugin is there if you go to "browse repositories..."

**Comment by etanshaul** [comment]
On second thought, I think its reasonable as long as we document it for developers on the github page.

**Comment by patflynn** [comment]
It's in our setup instructions:
https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/CONTRIBUTING.md

**Comment by etanshaul** [comment]
oh snap.

lgtm then.

**Pull request merged**
