### PR TITLE
Publish plugin to the nightly JB repo channel

### PR DESCRIPTION
**Pull request by etanshaul**
#1244 

Not exactly nightly, but a simple solution that uses the kokoro continuous integration for deployment to the nightly channel

### CODE REVIEW

**Comment by nkibler** [comment]
I've been thinking.. do we want to tie the continuous build to a nightly release like this? Would it make more sense to automate release cutting according to a schedule (i.e. nightly) and push it to different channels depending on the type of release we're making? I'm also not sure what's possible with Kokoro.

**Comment by etanshaul** [comment]
@nkibler, that was my original goal, but as far I could tell it isn't possible with Kokoro.

In terms of the types of channels, JB provides 3: the main release, "nightly", and "alpha". I was basically just re-purposing the nightly channel as a continuous deployment channel (makes it continuously up to date with master). Feel free to disagree with this approach though.

**Comment by etanshaul** [comment]
It looks like there are issues with this approach though. The continuous kokoro script is being run on PRs against master too which is not what we want.

**Comment by etanshaul** [comment]
closing for now since this doesn't work as intended.

**Pull request closed without merging**
