### PR TITLE
Fix Cloud Sdk panel validation messages

### LINKED ISSUE #1129: Cloud SDK panel missing java component error message is wrong
image

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #1129

### CODE REVIEW

**Comment by joaoandremartins** [comment]
How does this show a different message, for example, when the Cloud SDK validation shows that the Java components are missing?

Also, how do you feel about resolving the issue of the error message not appearing when the Settings window is open with an invalid SDK path in this PR? :X

**Comment by etanshaul** [comment]
It shows a different message because the apply method in AppEngineCloudConfigurable now delegates to the cloudSdkPanel to construct the message. CloudSdkPanel already had logic to construct a specific message, except that it was previously couple to toggling UI components. I just refactored CloudSdkPanel to separate out the message construction part so it can be reused.

I haven't thought about that other issue, but I'll see.

**Comment by joaoandremartins** [comment]
Ah, I see.

Well, this could be a good place for the other fix I mentioned. If you don't want it on this PR, feel free to merge.

**Comment by etanshaul** [comment]
sure. see https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1135 for more details on that other issue.

**Comment by joaoandremartins** [comment]
I'm not sure you understand what the issue I described is. :)

When you save an invalid SDK, close the settings window, then open it again, no error will be shown. You need to make a change to the path in order for the error message to show (if the new Cloud SDK is still invalid).

Maybe the best is for me to file a new issue.

**Comment by etanshaul** [comment]
I did understand but may not have done a good job describing it in that issue. feel free to modify that issue directly since that is what I intended it to represent

**Pull request merged**
