### PR TITLE
Release v16.11.6

### PR DESCRIPTION
**Pull request by etanshaul**

### CODE REVIEW

**Comment by patflynn** [comment]
how did this branch get out of date?

It's not ideal to have merges for these release PRs.

**Comment by etanshaul** [comment]
oh because I first merged in the update to the min SDK version in the changelog

**Comment by etanshaul** [comment]
since we squash it should be ok. but i'll try and remember to merge these release PRs quickly from now on

**Comment by patflynn** [comment]
np. I probably need to modify this release system somewhat.

**Pull request merged**
