### PR TITLE
Update BOM version label and version display text

### PR DESCRIPTION
**Pull request by etanshaul**
From offline discussions. Updates the BOM label and the version display.

image

### CODE REVIEW

**Comment by etanshaul** [comment]
@parkjam4 fyi

**Comment by etanshaul** [comment]
sounds good. I think this was @patflynn's suggestion too.

**Comment by etanshaul** [comment]
@patflynn @parkjam4, how you do feel about this wording?

**Comment by parkjam4** [comment]
LGTM

**Pull request merged**
