### PR TITLE
Improve deployment and staging error metrics

### PR DESCRIPTION
**Pull request by etanshaul**
#1241

### CODE REVIEW

**Comment by etanshaul** [comment]
Still looking at more ways to improve this

**Comment by patflynn** [comment]
We should update the common library to do staging using future's the same way the experimental deploy does.  I'd like to serialize all this code as much as possible. We've got node like code soup here which is hard to read.

**Comment by etanshaul** [comment]
yes, we indeed have callback hell here. I'll look at this in a different PR.

A common pattern we have with handling deployment/staging exception is something like this:

```
catch (SomeException se) {
  callback.errorOccured(someLocalizedMessage); // cancels the operation and sends the message to metrics
  logger.error(se); // IDE error and notifies us
}
```

@patflynn, @joaoandremartins  what are your thoughts on including the localized message in the logger.error and / or including the exception message in the callback errorOccured?

What I'm aiming for is a way to associate the localize message (e.g. "staging failed due to an unknown error") with the actual exception that was thrown. @patflynn I do remember you were against including localized messages in the logging statements.

Note: this will not help for cases where staging/deploy fails due to the process failing unsuccessfully (which is the majority of our failures). These cases still require updating gcloud's error messaging.

**Comment by patflynn** [comment]
@etanshaul why include localized message when you can just add your own more specific message to the error logging statement?

**Comment by etanshaul** [comment]
I don't think we have anything more specific to give. But on second thought, I don't think this will be helpful. We can already cross-reference the exception with the reported metric error with my current changes.

**Comment by etanshaul** [comment]
@patflynn, before I merge - did you have anything else in mind for this PR?

**Comment by patflynn** [comment]
nope.

**Pull request merged**
