### PR TITLE
Always sets automaticRestart to false in dev_appserver.

### LINKED ISSUE #972: Configuring the dev appserver to auto-restart on change seems to break things
Steps to reproduce:
1) Create a new app engine project using the wizard
2) configure the development server run config 'on frame deactivation' to 'update resources'
3) start the debugger in debug mode
4) modify index.jsp
5) navigate away from the editor

observed results:
dev server console outputs:
`Oct 10, 2016 5:05:39 PM com.google.appengine.tools.development.AbstractContainerService configure
WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)
Oct 10, 2016 5:05:39 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger
Oct 10, 2016 5:05:39 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: jetty-6.1.x
Oct 10, 2016 5:05:39 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Started SelectChannelConnector@localhost:50447
Oct 10, 2016 5:05:39 PM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:50447/
Oct 10, 2016 5:05:39 PM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:50447/_ah/admin
Oct 10, 2016 5:05:39 PM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart
INFO: Dev App Server is now running
Oct 10, 2016 5:05:39 PM com.google.appengine.tools.development.LocalResourceFileServlet doGet
WARNING: No file found for: /_ah/warmup
INFO     2016-10-10 17:05:39,771 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 404 83
INFO     2016-10-10 17:05:40,183 module.py:788] default: "GET / HTTP/1.1" 200 113
INFO     2016-10-10 17:05:40,190 module.py:788] default: "GET / HTTP/1.1" 200 113
INFO     2016-10-10 17:05:40,246 module.py:788] default: "GET / HTTP/1.1" 200 113
INFO     2016-10-10 17:05:40,615 module.py:788] default: "GET / HTTP/1.1" 200 113
INFO     2016-10-10 17:06:04,955 module.py:402] [default] Detected file changes:
  /usr/local/google/home/paflynn/IdeaProjects/nowayjose/out/artifacts/nowayjose_war_exploded/index.jsp
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
Disconnected from the target VM, address: '127.0.0.1:45362', transport: 'socket'
ERROR: transport error 202: connect failed: Connection refused
ERROR    2016-10-10 17:06:05,344 http_runtime.py:396] bad runtime process port ['']
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [../../../src/share/back/debugInit.c:750]
ERROR    2016-10-10 17:06:05,430 http_proxy.py:116] bad runtime process port ['']
INFO     2016-10-10 17:06:05,446 module.py:402] [default] Detected file changes:
  /usr/local/google/home/paflynn/IdeaProjects/nowayjose/out/artifacts/nowayjose_war_exploded/index.jsp
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
INFO     2016-10-10 17:06:05,531 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 500 285
ERROR    2016-10-10 17:06:05,827 http_runtime.py:396] bad runtime process port ['']
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [../../../src/share/back/debugInit.c:750]
ERROR    2016-10-10 17:06:05,829 http_proxy.py:116] bad runtime process port ['']
INFO     2016-10-10 17:06:05,930 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 500 285`

and the browser output is:
`bad runtime process port ['']

ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [../../../src/share/back/debugInit.c:750]`

### PR DESCRIPTION
**Pull request by joaoandremartins**
Removes that setting from the UI too.

Fixes #972

### CODE REVIEW

**Comment by patflynn** [comment]
@joaoandremartins seems like the new version of the library is not released yet.

**Comment by joaoandremartins** [comment]
@patflynn yep, I'm in the process of releasing it for the first time, but being caught up in a bunch of micro stuff

**Comment by patflynn** [comment]
Can you also add a note to the release notes? This should be the main thing the user is aware of being fixed when they update.

**Comment by joaoandremartins** [comment]
Yes, I'll do so in this PR.

**Comment by joaoandremartins** [comment]
Actually, just noticed this isn't done in a PR.

Added the following to the 16.10.4 release notes:

Fixed issue with debug session being aborted when HotSwap occurs. (#1027)

**Pull request merged**
