### PR TITLE
Remove setPosixFilePermissions.

### LINKED ISSUE #937: Flex deployment fails for Windows 10 users.
OS: Windows 10
Java: 1.8.0_112-release
IJ: 2016.2.4
plugin: 1.0-BETA-0.2

__NONE___
error.message	
null
error.stacktrace	
java.lang.UnsupportedOperationException
	at java.nio.file.Files.setPosixFilePermissions(Files.java:2044)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineFlexibleStage.stage(AppEngineFlexibleStage.java:63)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineFlexibleDeployTask.execute(AppEngineFlexibleDeployTask.java:68)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineExecutor.run(AppEngineExecutor.java:37)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:793)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:629)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

### PR DESCRIPTION
**Pull request by joaoandremartins**
Fixes #937

### CODE REVIEW

**Comment by etanshaul** [comment]
I'm wondering a couple things:

1) what determines the default permissions for the file and does it behave consistently / system-independently
2) is there any value in catching the exception to handle the windows case, but still setting the permissions on posix compliant systems?

**Comment by joaoandremartins** [comment]
@etanshaul I added some reasoning on #937. I don't think we need this call, even on posix compliant systems.

**Comment by chanseokoh** [comment]
On Linux where a user uses a umask of, say, 027 such as our corporate desktops, we needed this permission setting to ensure that the artifact has the other read permission. Otherwise, Jetty on GAE cannot load the app, causing GAE to respawn VMs endlessly.

**Comment by patflynn** [comment]
I thought we had pushed this down into the common library...

**Comment by etanshaul** [comment]
flex staging still does some work on our end. that being said we can (and should I think) defer to the library entirely. This has a dependency on https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/451

**Comment by aslo** [comment]
:+1: LGTM

**Comment by etanshaul** [comment]
lgtm since @chanseokoh confirmed that the permission setting is no longer an issue

**Pull request merged**
