### PR TITLE
Update Cloud API dialog and action/menu wording.

### LINKED ISSUE #2240: Update wording for non-Maven Cloud APIs dialog to reduce user confusion
After implementing #2214, major labels and titles still suggest Cloud API dialog will do something with the actual project/module libraries rather than just prepare and enable APIs on GCP and create service accounts.

Update the following to avoid using "add libraries" and keep the original names only for Maven projects:
1. Action name / menu item text
2. Dialog title
3. All custom named buttons like "Add Client Library" used instead of "OK" in the dialog.

### PR DESCRIPTION
**Pull request by ivanporty**
Fixes #2240.
Will be followed up and completed with #2241.

Removes confusion for non-Maven cases where a user can only enable and manage Cloud APIs but not specific project/language libraries.

Maven project dialog:
cloud-apis-maven

Non-Maven (any language) project dialog:
cloud-api-plainjava

Menu item text by default (non-Maven):
menu-apis-non-maven

### CODE REVIEW

**Comment by etanshaul** [comment]
The Action text and the dialog header look good.

The button "Select Cloud API" feels a bit strange on first glance (could just be me though). For one, the use could select multiple APIs, not just one. Maybe "Select Cloud API(s)"? @parkjam4 maybe can comment on the styleguide for doing that.

The other options is maybe just something like "Continue".

**Comment by ivanporty** [comment]
I was hesitant about this too, but we originally used "Add Client Library" as a button text although multiple libraries can be selected so I followed that path. Looking for suggestions here.

**Comment by etanshaul** [comment]
I was trying to find some existing examples of this in IntelliJ without much luck. One other think I was thinking is that the action should have a trailing `...` to indicate that more things will happen before its applied

**Comment by etanshaul** [comment]
maybe just "Continue ..." (and I possible use this wording regardless of Maven vs no Maven). wdyt?

**Comment by ivanporty** [comment]
I read a bit on ellipsis in buttons and it might be a suitable case, so neutral `Continue...` should work too. I'll do the change while we wait for input from @parkjam4.

**Comment by parkjam4** [comment]
I like the use of Continue, but I don't think we need the ellipse here since Continue already implies that additional steps are coming.

**Pull request merged**
