### PR TITLE
Proper application service interface override

### LINKED ISSUE #2125: Runtime errors when launching the IDE
Happens just on booting the IDE, on master. Doesn't seem to affect functionality.

```
java.lang.RuntimeException: Service: com.google.cloud.tools.intellij.cloudapis.ServiceAccountKeyDialogService doesn't override anything
	at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:77)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:70)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.addExtensionPointListener(ExtensionPointImpl.java:405)
	at com.intellij.openapi.components.impl.ServiceManagerImpl.installEP(ServiceManagerImpl.java:101)
	at com.intellij.openapi.components.impl.ServiceManagerImpl.<init>(ServiceManagerImpl.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:459)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:240)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:207)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$8(ApplicationImpl.java:398)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:68)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:413)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #2125 

The UE service definition in plugin.xml uses an override to inject a different impl for UE. Previously, it was overriding a concrete class (which for some reason was working, but now we get the error in #2125).

This updates the base service to an interface with a CE, and UE implementation.

### CODE REVIEW

**Comment by etanshaul** [comment]
looks like the error didn't go away with this fix. investigating whats going on...

**Comment by ivanporty** [comment]
Damn.. I feel it appeared after the latest re-shuffle of plugin modules, same as EAP failures, some dependencies might have broken.

**Comment by etanshaul** [comment]
I'm seeing inconsistent results: when I first tested this fix it removed the error and fixed the functionality. Now I'm seeing otherwise. It may be that i'm not starting with a clean build. I'll investigate.

**Comment by etanshaul** [comment]
I suspect my fix didn't address the actual issue:

The plugin.xml service override is in the appengine:ultimate configuration. The service that is being overriden (in this case) lives in the cloud-apis module. Depending on the load order (appengine ultimate, vs cloud-apis) we can get this error. I.e. if appengine:ultimate is loaded first, then the `override="true"` runtime error will occur because there is nothing yet for it to override. Similarly the overriding feature won't work because the "original" implementation in cloud-apis will be loaded later.

**Comment by etanshaul** [comment]
I think the cloud-tools-plugin plugin.xml optional dependencies are order-sensitive. Testing this out.

**Comment by etanshaul** [comment]
this is not the correct fix for the issue. closing.

**Pull request closed without merging**
